### ISSUE TITLE
How to use CUDA ?

### ISSUE THREAD

**Issue by allenpeng88** [dme-compunet/YOLOv8#11]
Hi, 

how to use cuda in Yolov8 ? I found it only installed Microsoft.ML.OnnxRuntime by Nuget tool. when I used SessionOptions add cuda, throw a error "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'."

**Comment by dme-compunet** [comment]
Try adding reference to `Microsoft.ML.OnnxRuntime.Gpu` package, and I'd appreciate feedback if that helped.

**Comment by allenpeng88** [comment]
<img width="228" alt="test" src="https://github.com/dme-compunet/YOLOv8/assets/24827554/b356e091-d428-4889-8708-0f5423d27c52">

Can not replace 'Microsoft.ML.OnnxRuntime' by Microsoft.ML.OnnxRuntime.Gpu, how to deal with it.

Thanks a lot.

**Comment by dme-compunet** [comment]
Temporarily try to change the `YoloV8` package version to `1.2.0` and see if that solves the problem.

I am considering creating another nuget package called `YoloV8.Gpu`, that will contain the reference to `Microsoft.ML.OnnxRuntime.Gpu`.

**Comment by dme-compunet** [comment]
Try changing `YoloV8` package to `YoloV8.Gpu`

**Comment by oneprofittips** [comment]
Good afternoon. How to make it so that on systems where there is a GPU used it, and where there is not, the CPU was used.

**Comment by dme-compunet** [comment]
> How to make it so that on systems where there is a GPU used it, and where there is not, the CPU was used.

How do you do it with ONNX-Runtime? from what I understand (I have no experience with this) it is impossible to install `Microsoft.ML.OnnxRuntime` and `Microsoft.ML.OnnxRuntime.Gpu` together.

**Comment by ErrorGz** [comment]
First of all, thank you for your yolov8.net code. I tested the CUDA version, and it was able to load the model, but it didn't work properly during inference. The program exits without any error message. (The CPU version can perform inference correctly).

首先，感谢你的yolov8.net代码。我测试了cuda版本，能装载模型，但是推理的时候不能正常工作，他的现象是程序退出，没有什么提示。（CPU版本可以正常推理）

**Comment by dme-compunet** [comment]
Hi @FunJoo, a few days ago I published the [YoloV8.Gpu](https://www.nuget.org/packages/YoloV8.Gpu) nuget package, which contains reference to `Microsoft.ML.OnnxRuntime.Gpu`, so he can use it without cloning the source code.

**Comment by oneprofittips** [comment]
This is the error I get when trying to work through the GPU

` Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Admin\Desktop\ObjDetector\onnxruntime_providers_cuda.dll"

         at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
         at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
         at ObjDetector.Services.FindObjectImgService..ctor(ILogger`1 logger, IConfiguration configuration) in D:\Shared\sharpprogects\ObjDetector\ObjDetector\Services\FindObjectImgService.cs:line 22
         at InvokeStub_FindObjectImgService..ctor(Object, Object, IntPtr*)
         at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method3(Closure, IServiceProvider, Object[])
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at ObjDetector.Middlewares.RequestTimingMiddelware.InvokeAsync(HttpContext context) in D:\Shared\sharpprogects\ObjDetector\ObjDetector\Middlewares\RequestTimingMiddelware.cs:line 17
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Comment by FunJoo** [comment]
@oneprofittips 
While I was testing the impact of different cuDNN versions on my project, I think I've successfully replicated the issue you encountered. It seems you didn't successfully install the cuDNN library for CUDA.
![pic](https://github.com/dme-compunet/YOLOv8/assets/30665751/7711d560-c58e-4d2f-a38a-0c6e34a384e9)

**Comment by FunJoo** [comment]
@ErrorGz 
1、我以前遇到过引用第三方.dll，然后debug中无任何报错直接闪退的情况。这种情况一般是环境配置问题，或许和本仓库代码关系不大，建议检查你的cuda和cudnn版本是否和onnxruntime匹配，参考链接：https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements
2、你应该是使用的nuget包才会catch不到Exception的，可以尝试拉取源码调试看看。
……
最后想说的就是，其实我原本打算不回你了（建议你继续使用英语提问以寻求其他人的帮助），因为你提供的信息不足以复刻你遇到的问题。不过刚好就是，这两天我在一台旧电脑上运行本仓库代码，也遇到类似环境问题（附图两张）。我应该是不会提交新issue了，如果你catch到的Exception类似，我解决这些环境问题之后可以在这个issue把结果告诉你。
![001](https://github.com/dme-compunet/YOLOv8/assets/30665751/764bf90c-f3b9-463f-8363-e0980ccd40ee)
![002](https://github.com/dme-compunet/YOLOv8/assets/30665751/021a8cfc-b7de-4dda-a177-4699a684338a)

**Comment by dme-compunet** [comment]
@oneprofittips This is more related to onnxruntime, see: https://github.com/microsoft/onnxruntime/issues?q=LoadLibrary+failed+with+error+126

**Comment by ErrorGz** [comment]
@FunJoo @dme-compunet
Thank you for your assistance. I have successfully used CUDA for inference. Here's a rundown of the steps I took:

Added the path to cuda/bin in the PATH environment variable. In my case, it was C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin.
Added the zlibwapi.dll file to the program directory.

**Comment by ckmstydy** [comment]
> This is the error I get when trying to work through the GPU
> 
> ` Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] D:\a_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\Admin\Desktop\ObjDetector\onnxruntime_providers_cuda.dll"
> 
> ```
>      at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
>      at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
>      at ObjDetector.Services.FindObjectImgService..ctor(ILogger`1 logger, IConfiguration configuration) in D:\Shared\sharpprogects\ObjDetector\ObjDetector\Services\FindObjectImgService.cs:line 22
>      at InvokeStub_FindObjectImgService..ctor(Object, Object, IntPtr*)
>      at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>      at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
>      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
>      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
>      at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
>      at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
>      at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>      at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
>      at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
>      at lambda_method3(Closure, IServiceProvider, Object[])
>      at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
>   --- End of stack trace from previous location ---
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
>   --- End of stack trace from previous location ---
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>      at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>      at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>      at ObjDetector.Middlewares.RequestTimingMiddelware.InvokeAsync(HttpContext context) in D:\Shared\sharpprogects\ObjDetector\ObjDetector\Middlewares\RequestTimingMiddelware.cs:line 17
>      at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
>      at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>      at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>      at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`
> ```

Have you solved the problem? I had the same problem
