### ISSUE TITLE
Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_ROCM' in shared library 'onnxruntime'.

### ISSUE THREAD

**Issue by daniliammo** [dme-compunet/YoloV8#77]
**Unhandled exception**. 
```
System.EntryPointNotFoundException: Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_ROCM' in shared library 'onnxruntime'.
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtSessionOptionsAppendExecutionProvider_ROCM(IntPtr options, Int32 device_id)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_ROCm(Int32 deviceId)
   at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithRocmProvider(Int32 deviceId)
   at SkyNet.SkyNet.LoadYoloPredictor(String modelPath) in /home/daniliammo/RiderProjects/SkyNet/SkyNet/SkyNet.cs:line 30
```

**Code:**
```csharp
    private static void LoadYoloPredictor(string modelPath)
    {
        var x = new YoloPredictorOptions
        {
            UseCuda = false,
            SessionOptions = SessionOptions.MakeSessionOptionWithRocmProvider() // AMD GPU
        };
        _yoloPredictor = new YoloPredictor(modelPath, x);
        Console.WriteLine("YoloPredictor ready!");
    }
```

**But this code works:**
```csharp
    private static void LoadYoloPredictor(string modelPath)
    {
        var x = new YoloPredictorOptions
        {
            UseCuda = false // CPU
        };
        _yoloPredictor = new YoloPredictor(modelPath, x);
        Console.WriteLine("YoloPredictor ready!");
    }
```

**OS: Fedora Linux 40
**Kernel:** Linux 6.10.12-200.fc40.x86_64
Packages:**
![installedpackages](https://github.com/user-attachments/assets/cfe36c6c-76d3-4877-afc5-a1e9095717dc)
bin/Debug/net8.0:
![dlls](https://github.com/user-attachments/assets/c3101b62-ba36-41ef-81dd-ee2dd65432b0)

**Comment by dme-compunet** [comment]
Sorry, I have no experience with `amd` and `rocm`, but in any case the issue is not directly related to this repo, It is more related to https://github.com/microsoft/onnxruntime you may get an answer there
